#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# ODWS Documentation Translation Script
#
# Default behavior:
# - translates ONLY missing files
# - prints INFO when a file is created
# - silent when nothing changes
#
# Flags:
#   DEBUG=true   → verbose decision log
#   FORCE=true   → retranslate everything
#   OFFLINE=true → no network, copy-only (dry run)
# ============================================================

SOURCE_LANG="en"
TARGET_LANGS=("cs" "de" "fr" "ru")
DOCS_DIR="docs"

DEBUG="${DEBUG:-false}"
FORCE="${FORCE:-false}"
OFFLINE="${OFFLINE:-false}"

# ------------------------------------------------------------
# Logging helpers
# ------------------------------------------------------------

debug() {
  [[ "$DEBUG" == "true" ]] && echo "[DEBUG] $*"
}

info() {
  echo "[INFO] $*"
}

# ------------------------------------------------------------
# Translation backend
# ------------------------------------------------------------

translate() {
  local lang="$1"

  if [[ "$OFFLINE" == "true" ]]; then
    cat
    return
  fi

  if command -v trans >/dev/null 2>&1; then
    trans -b :"$lang" 2>/dev/null || cat
  else
    cat
  fi
}

# ------------------------------------------------------------
# Translate one file if needed
# ------------------------------------------------------------

translate_file() {
  local src="$1"
  local lang="$2"
  local dst="$3"

  # Skip existing unless FORCE=true
  if [[ -f "$dst" && "$FORCE" != "true" ]]; then
    debug "Skipping existing: $dst"
    return
  fi

  mkdir -p "$(dirname "$dst")"

  if [[ -f "$dst" ]]; then
    info "Recreating: $dst"
  else
    info "Creating:   $dst"
  fi

  # Extract first HTML comment as metadata
  metadata="$(sed -n '1,/-->/p' "$src")"
  body="$(sed '1,/-->/d' "$src")"

  {
    echo "> ⚠ This file is auto-generated from docs/en/$(basename "$src")."
    echo "> The authoritative version is the English original."
    echo "> Do not edit this file manually."
    echo
    echo "$metadata"
    echo
    printf "%s\n" "$body" | translate "$lang"
  } > "$dst"
}

# ------------------------------------------------------------
# Main
# ------------------------------------------------------------

debug "Starting documentation translation"

for lang in "${TARGET_LANGS[@]}"; do
  debug "Processing language: $lang"

  for src in "$DOCS_DIR/$SOURCE_LANG"/*.md; do
    filename="$(basename "$src")"
    dst="$DOCS_DIR/$lang/$filename"

    translate_file "$src" "$lang" "$dst"
  done
done

debug "Translation finished"
