#!/usr/bin/env bash
set -euo pipefail

# ============================
# CONFIG
# ============================

SOURCE_LANG="en"
TARGET_LANGS=("cs" "de" "fr" "ru")
DOCS_DIR="docs"

DEBUG="${DEBUG:-false}"
OFFLINE="${OFFLINE:-false}"
FORCE="${FORCE:-false}"

# ============================
# LOGGING
# ============================

log() {
  [[ "$DEBUG" == "true" ]] && echo "[DEBUG] $*"
}

# ============================
# TRANSLATION BACKEND
# ============================

translate() {
  local lang="$1"
  if [[ "$OFFLINE" == "true" ]]; then
    cat
  else
    trans -b :"$lang" 2>/dev/null || cat
  fi
}

# ============================
# TRANSLATE SINGLE FILE
# ============================

translate_file() {
  local src="$1"
  local lang="$2"
  local dst="$3"

  # pokud cílový soubor existuje a není FORCE, přeskoč
  if [[ -f "$dst" && "$FORCE" != "true" ]]; then
    log "↷ Skipping existing: $dst"
    return
  fi

  log "→ Translating: $src → $dst"

  # metadata = první HTML komentář
  metadata="$(sed -n '1,/-->/p' "$src")"

  # body = vše za metadata
  body="$(sed '1,/-->/d' "$src")"

  {
    echo "> ⚠ This file is auto-generated from docs/en/$(basename "$src")."
    echo "> The authoritative version is the English original."
    echo "> Do not edit this file manually."
    echo
    echo "$metadata"
    echo
    printf "%s\n" "$body" | translate "$lang"
  } > "$dst"
}

# ============================
# MAIN
# ============================

log "Starting documentation translation"

for lang in "${TARGET_LANGS[@]}"; do
  target_dir="$DOCS_DIR/$lang"
  mkdir -p "$target_dir"

  for src in "$DOCS_DIR/$SOURCE_LANG"/*.md; do
    filename="$(basename "$src")"
    dst="$target_dir/$filename"

    translate_file "$src" "$lang" "$dst"
  done
done

log "Translation finished"
