#!/usr/bin/env bash

set -e

SOURCE_LANG="en"
TARGET_LANGS=("cs" "de" "fr" "ru")

# -----------------------------
# Translate docs/
# -----------------------------
for lang in "${TARGET_LANGS[@]}"; do
  for file in docs/$SOURCE_LANG/*.md; do
    name=$(basename "$file")
    echo "Generating docs/$lang/$name"
    cat <<EOF > docs/$lang/$name
> ⚠ This file is auto-generated from docs/en/$name.
> Do not edit manually.

$(cat "$file")
EOF
  done
done

# -----------------------------
# Translate main README.md
# -----------------------------
if [[ -f README.md ]]; then
  for lang in "${TARGET_LANGS[@]}"; do
    target="README.$lang.md"
    echo "Generating $target"
    cat <<EOF > "$target"
> ⚠ This is an automatically generated translation of README.md.
> The authoritative version is README.md (English).
> Do not edit this file manually.

$(cat README.md)
EOF
  done
fi
